out_dir: results
metric_best: accuracy
metric_agg: argmin
wandb:
  use: True
  project: MUTAG
dataset:
  format: PyG-TUDataset
  name: MUTAG
  task: graph
  task_type: classification_binary
  transductive: False
  split_mode: random
  node_encoder: True
  node_encoder_name: TypeDictNodeOneHot+RWSE
  node_encoder_num_types: 7
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: TypeDictEdgeOneHot
  edge_encoder_num_types: 4
  edge_encoder_bn: False
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,51)
  model: Linear
  dim_pe: 69
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: GPSModel
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add
gt:
  layer_type: GINE+Transformer  # CustomGatedGCN+Performer
  layers: 2
  n_heads: 6
  dim_hidden: 90  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  attn_dropout: 0.1
  layer_norm: False
  batch_norm: True
gnn:
  head: san_graph
  layers_pre_mp: 0
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 90  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: False
  optimizer: adam
  weight_decay: 0.0
  base_lr: 0.0003
  max_epoch: 300
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 10
